### ISSUE TITLE
esm vs cjs

### ISSUE THREAD

**Issue by matt-erhart** [xHomu/remix-v2-server#3]
Thanks for making these examples, helped me debug an import issue I was having with https://mui.com/base-ui/getting-started/quickstart/. I can't get it to install with 'esm' but I can with 'cjs' (ts). Do you happen to know why that is, so I can better reason about esm vs cjs in the future?

**Comment by xHomu** [comment]
Unfortunately, some packages are just very difficult/impossible to use in ESM-land until they fix their bundle exports. I'm not sure if MUI is one of them, so you may better ask at their page about ESM support.

BTW, it's perfectly okay to stay with CJS. When Remix v2 finally ships, as long as you have the `serverModuleFormat: "cjs",` prop in `remix.config`, your app will be just fine.
