### ISSUE TITLE
ESM + TS reloading node_modules

### ISSUE THREAD

**Issue by jaschaio** [xHomu/remix-v2-server#4]
I am following the [ES Modules + typescript example](https://github.com/xHomu/remix-v2-server/commit/ba20097d5739e676d986f8e667b53dfcd059e578) and it works fine for UI changes and as well for anything that is placed within `serverDependenciesToBundle`. But I have some other monorepo dependencies that are not bundled into the server (so coming from `node_modules`), included within [`watchPaths`](https://remix.run/docs/en/1.17.1/file-conventions/remix-config#watchpaths) but that don't get updated when the server reloads.

It makes sense because I am only ["cache busting" the `BUILD_PATH`](https://github.com/xHomu/remix-v2-server/commit/ba20097d5739e676d986f8e667b53dfcd059e578#diff-1ba718c1eb8aa39cd20c2562d92523068c734d75f54655e97d652b992d9b4259R99) but nothing from `node_modules` – any suitable approach to cache bust as well specific node_modules? Maybe by implementing a custom loader on top of `ts-node`?

**Comment by xHomu** [comment]
I'm not too familiar with monorepo setups with Remix. Sorry!

You might be able to get some help over at the Remix repo discussions or Remix Discord https://rmx.as/discord
