### ISSUE TITLE
missing await

### ISSUE THREAD

**Issue by h3har** [xHomu/remix-v2-server#7]
broadcastDevReady is not marked as async by Remix's `.d.ts` files but it actually is an async and returns a `Promise<void>`, you need an await there (there are two calls in `server.ts` that need updating).

I had big issues with it not updating properly and I changed this and it works properly now, so I suspect that was an issue. Maybe it could still work without the await but it could become a race condition, not sure. But it works now.

Otherwise, great template :-)

**Comment by h3har** [comment]
Okay well I'm still having some reloading issues so maybe `await` wasn't an issue. Not sure if it's still an issue in general.

**Comment by xHomu** [comment]
Try bumping node to v20 if you're having LiveReload issues with the most recent Remix releases. 

Saw this reported on the Discord, give it a shot!
